server:
  port: ${PORT:4985}

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:./hexlet
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

# BEGIN
#  swagger-ui:
#    path: http://localhost:4985/swagger.html
springdoc.swagger-ui.path: /swagger.html
# END
